name: Hotfix-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version to update"
        required: true
      prerelease:
        required: true
        type: boolean
        description: Is this a pre-release

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: setup git
        run: |
          git config user.name "Github Actions"
          git config user.email "info@netmaker.io"
      - name: create release branch
        run: |
          git switch release_${{ github.event.inputs.version }}
      - name: update-tag
        run: |
          git tag -f ${{ github.event.inputs.version }}
          git push
  
  linux-headless:
    runs-on: ubuntu-latest
    needs: update-tag
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: release_${{ github.event.inputs.version }}
          fetch-depth: 0
      - run: |
          git fetch --force --tags
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: goreleaser (full release)
        if: ${{ github.event.inputs.prerelease == 'false'}}
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean --release-notes release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: goreleaser (prerelease)
        if: ${{ github.event.inputs.prerelease == 'true'}}
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean --release-notes release.md -f .goreleaser.prerelease.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        
  freebsd-headless:
    runs-on: ubuntu-latest
    needs: update-tag
    steps:
      - name: build freebsd
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: freebsd.clustercat.com
          username: freebsd
          key: ${{ secrets.TESTING_SSH_KEY }}
          script: |
            cd netclient
            git fetch
            git switch release_${{ github.event.inputs.version }}
            git restore .
            git pull
            go build -tags headless .
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_devops
          chmod 600 ~/.ssh/id_devops
          cat >>~/.ssh/config <<END
          Host *.clustercat.com
            User freebsd
            IdentityFile ~/.ssh/id_devops
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.TESTING_SSH_KEY }}
      - name: get freebsd binary
        run: |
          scp freebsd@freebsd.clustercat.com:~/netclient/netclient /tmp/
      - name: upload freebsd to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/netclient
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          asset_name: netclient-freebsd-amd64


  docker:
    needs: update-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release_${{ github.event.inputs.version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          tags: gravitl/netclient:${{ github.event.inputs.version }}
  
  packages:
    if: ${{ github.event.inputs.prerelease == 'false' }}
    needs: update-tag
    uses: ./.github/workflows/packages.yml
    with:
      version: ${{ github.event.inputs.version }}

  pull-request:
    if: ${{ github.event.inputs.prerelease == 'false' }}
    needs: update-tag
    uses: ./.github/workflows/pull-request.yml
    with:
      version: ${{ github.event.inputs.version }}
